NAME=beano
VERSION=1.0.0
# uncomment for envs like mac + homebrew
#CGO_CFLAGS="-I/usr/local//Cellar/leveldb/1.18/include/ -I/usr/local/Cellar/snappy/1.1.1/include/" 
#CGO_LDFLAGS="-L/usr/local//Cellar/leveldb/1.18/lib -L/usr/local//Cellar/snappy/1.1.1/lib"

